Added Player FAQ & info about how to link Discord account
BeamMP/Docs pull request #15
Opened 2024-01-29 20:41 UTC by Starystars67

I also fixed some links in this.

Please can we get as many locales updated to support this PR before merging?

@lionkor @AlexITA1100 maybe I could ask you to assist in getting some of the translations done/checked? (IT,RU,DE)

2024-01-30 05:55 UTC, lionkor commented
@Dash-kor

2024-01-30 09:30 UTC, AlexITA1100 requested changes

2024-01-30 09:30 UTC, AlexITA1100 commented on docs/en/support/player-faq.md
The following paragraphs should not be here as they're already in `game-faq.md`. This file should only answer questions about the player (sign up/linking Discord/Early Access benefits), not the compatibility of the game nor its performance.
- My game keeps freezing when other players edit or spawn vehicles
- How do I install BeamMP?
- Does BeamMP works on a cracked version of BeamNG.drive?
- Does BeamMP work on Linux?
- Why is the launcher flagged by my antivirus or by Windows Defender?
- I have poor performance / low FPS, what should I do?

2024-01-30 13:01 UTC, Starystars67 commented on docs/en/support/player-faq.md
Spot on, yep agreed.

2024-01-30 13:33 UTC, Starystars67 commented on docs/en/support/player-faq.md
> +## I have more questions?
Done something along these lines.

2024-01-30 14:26 UTC, AlexITA1100 commented on docs/en/support/player-faq.md
> +If your question or issue relates to the Game or playing please refer to the [Game FAQs](support/game-faq.md).
This leads to 404, should be only `(game-faq.md)`, sorry about that.

2024-01-30 14:26 UTC, AlexITA1100 commented on docs/en/support/player-faq.md
> +If your question or issue relates to running a Server please refer to the [Server FAQs](support/server-faq.md).
This leads to 404, should be only `(server-faq.md)`, sorry about that.

2024-01-30 15:11 UTC, AlexITA1100 approved these changes

2024-01-31 08:44 UTC, Starystars67 commented
Lets just wait on Russian translation for this too and then we can merge, thank everyone

2024-02-16 14:46 UTC, merged