Update error-codes.md
BeamMP/Docs pull request #49
Opened 2024-07-11 17:52 UTC by Protogen187

Added Codes 10048 and 10038/10060/10061

2024-07-11 18:05 UTC, O1LER requested changes
I think it should be clearer that 10048 is an issue between launcher and game, its mostly (if not exclusively) caused by another launcher already running.

Whereas the other three are caused by the server setup, so the user (if not also hosting the server) cant do anything about it other than choosing a different server.

Also check other docs pages for internal links, to link to the server installation page instead of just mentioning it

2024-07-12 19:36 UTC, O1LER reviewed
What do you think about this @Protogen187 ?

2024-07-12 21:07 UTC, Protogen187 reviewed
I'd approve but I can't

2024-07-12 21:07 UTC, ELKER54 approved these changes

2024-07-12 21:10 UTC, O1LER approved these changes

2024-07-12 21:11 UTC, merged