Updates FAQs
BeamMP/Docs pull request #6
Opened 2023-12-26 11:29 UTC by AlexITA1100

- Updated dead links;
- Updated server on Linux FAQs;
- Both FAQs have the same structure now;
- Added table for code licenses;
- Added Italian localisation for the FAQs;

Resolves #5

2023-12-27 15:36 UTC, Starystars67 approved these changes
Thank you @AlexITA1100 for helping with a lot of this kind of work at the moment. 
<3

2023-12-28 14:43 UTC, 20dka requested changes

2023-12-28 14:43 UTC, 20dka commented on docs/en/support/game-faq.md
> +Before doing anything keep in mind that the code is under [Terms of Use](https://forum.beammp.com/t/terms-of-use-v1-0/43).
I'm not sure about the wording here. Could you maybe change it to:

> Before doing anything keep in mind that the code is subject to our Terms of Use and Licenses:

Thanks.

2023-12-28 14:43 UTC, 20dka commented on docs/en/support/server-faq.md
> +Before doing anything keep in mind that the code is under [Terms of Use](https://forum.beammp.com/t/terms-of-use-v1-0/43).
see other comment

2023-12-28 20:14 UTC, Starystars67 approved these changes
This looks much better too!

2023-12-28 23:35 UTC, lionkor requested changes

2023-12-28 23:35 UTC, lionkor commented on docs/en/support/server-faq.md
> +All the information to setup your own server can be found [here](https://docs.beammp.com/server/create-a-server/).
```suggestion
All the information to set up your own server can be found [here](https://docs.beammp.com/server/create-a-server/).
```

2023-12-31 14:19 UTC, Starystars67 approved these changes

2024-01-03 11:21 UTC, Starystars67 approved these changes

2024-01-03 11:47 UTC, lionkor approved these changes

2024-01-03 11:47 UTC, merged