Update game-faq.md
BeamMP/Docs pull request #63
Opened 2024-08-28 10:27 UTC by Protogen187

- Changed the wording in some sentences
- Removed "known issues" from title since there are no known issues posted in the file
- mentioned that a legit copy of BeamNG.Drive is needed for BeamMP to operate (since pirated copies are not supported)

2024-08-28 11:04 UTC, Protogen187 commented on docs/en/support/game-faq.md
> +For BeamMP to be a trusted source for various Antivirus programs, a very expensive licecence would be needed.
Thank you for pointing this out

2024-08-28 11:15 UTC, Protogen187 commented on docs/en/support/game-faq.md
> +BeamMP does not work with cracked versions or outdated versions of BeamNG.drive. If you want to use BeamMP, you need to own a legit copy of BeamNG.Drive off Steam.
I'd leave it at "legit"

2024-08-28 12:11 UTC, Starystars67 commented on docs/en/support/game-faq.md
> +BeamMP does not work with cracked versions or outdated versions of BeamNG.drive. If you want to use BeamMP, you need to own a legit copy of BeamNG.Drive off Steam.
Also "off steam" should be "from Steam".

2024-08-28 12:24 UTC, Protogen187 commented on docs/en/support/game-faq.md
> +BeamMP does not work with cracked versions or outdated versions of BeamNG.drive. If you want to use BeamMP, you need to own a legit copy of BeamNG.Drive off Steam.
I fixxed it

2024-09-28 20:14 UTC, Protogen187 commented
Cannot approve requested changes myself.
Need to wait for someone else to do so.

2024-09-28 20:25 UTC, ELKER54 commented on docs/en/support/game-faq.md
> +Some antivirus prgroams may flag BeamMP as a threat, due to it interacting with the network and other stuff. There are **no viruses** in any of the code. The code for the launcher, server, and lua cl
programs not prgroams

2024-09-28 20:32 UTC, Protogen187 commented
@lionkor I made the changes

2024-10-04 14:47 UTC, O1LER requested changes

2024-10-04 14:47 UTC, O1LER commented on docs/en/support/game-faq.md
> +BeamMP is not guaranted not work with cracked versions or outdated versions of BeamNG.drive.
`BeamMP is not guaranteed to work with`
or
`BeamMP may not work with`

2024-10-04 14:47 UTC, O1LER commented on docs/en/support/game-faq.md
> +We are working hard to make the Multiplayer experience as stable as possible. If you have already lowered your graphic settings and your performance is still poor, consider playing on a server with l
`One car uses one CPU thread`
or
`1 car uses 1 CPU thread`

also im not sure if we even want to include this. Its technically not correct, its more of a rule of thumb

2024-10-06 18:36 UTC, ELKER54 commented on docs/en/support/game-faq.md
> +We are working hard to make the Multiplayer experience as stable as possible. If you have already lowered your graphic settings and your performance is still poor, consider playing on a server with l
I would say leave it, we recommend it but its not a rule. Lots of people get good frames with lower core cpus, with high pops

2024-10-06 21:29 UTC, Protogen187 reviewed
grammar fix

2024-10-07 03:34 UTC, O1LER approved these changes

2024-10-22 07:15 UTC, Protogen187 commented
@lionkor Awaiting approval

2024-10-24 16:57 UTC, Starystars67 commented on docs/en/support/game-faq.md
> +Some antivirus programs may flag BeamMP as a threat, due to it interacting with the network and other stuff. There are **no viruses** in any of the code. The code for the launcher, server, and lua cl
Though correct the wording here feels off. 

Please rereview this bit.

2024-10-26 20:15 UTC, ELKER54 approved these changes
LGTM

2024-10-26 20:18 UTC, O1LER approved these changes

2024-10-26 20:18 UTC, O1LER commented on docs/en/support/game-faq.md
> +Some antivirus programs may flag BeamMP as a threat, due to it interacting with the network and other stuff. There are **no viruses** in any of the code. The code for the launcher, server, and lua cl
Please open a new PR changing this, theres lots of other bits that need to be merged in order to enable translating

2024-10-26 20:18 UTC, merged